/**
 * Snapshot temporal de la planilla real (66 libros), tomado a mano hasta
 * que la dueña publique la Google Sheet como CSV. Reemplazar `getBooks()`
 * en `books.ts` para leer desde la URL publicada en vez de este snapshot.
 */
export const rawBooksCsv = `Libro,Autor/a,Estado,Precio,Stock
"Amor, culpa y reparación","Melanie Klein","Usado","$6.000,00","Disponible"
"Antes que se enfríe el café","Toshikazu Kawaguchi","Usado","$15.000,00","Disponible"
"Angeles y demonios","Dan Brown","Usado","$10.000,00","Disponible"
"A Sangre Fría","Truman Capote","Usado","$6.000,00","Disponible"
"Bowie","Simon Critchley","Usado","$8.000,00","Disponible"
"Café cantante","Antonio Gala","Usado","$4.000,00","Disponible"
"Catedrales","Claudia Piñeiro","Usado","$18.000,00","Disponible"
"Conversaciones entre amigos","Sally Rooney","Usado","$14.000,00","Vendido"
"Colorado Kid","Stephen King","Usado","$6.000,00","Disponible"
"Cuentos cansados","Mario Levrero","Usado","$13.000,001000$","Disponible"
"Dr Jekyll and Mr Hyde (Inglés)","Robert Louis Stevenson","Usado","$4.000,00","Disponible"
"Diario de un Colibrí","Cinwololo","Usado","$7.000,00","Vendido"
"El Amante","Marguerite Duras","Usado","$10.000,00","Disponible"
"El amante Japonés","Isabel Allende","Usado","$8.000,00","Vendido"
"El asedio animal","Vanesa Londoño","Usado","$6.000,00","Disponible"
"El desbarrancadero","Fernando Vallejo","Usado","$19.000,00","Disponible"
"El diario de Bridget Jones","Helen Fielding","Usado","$7.000,00","Disponible"
"El horror de Dunwich","H.P. Lovecraft","Usado","$7.000,00","Disponible"
"El Hobbit","Tolkien, J. R. R.","Usado","$9.000,00","Disponible"
"El malentendido Calígula","Albert Camus","Usado","$6.000,00","Disponible"
"El niño con el pijama de rayas","John Boyne","Usado","$7.000,00","Disponible"
"Érase una vez en Hollywood","Quentin Tarantino","Usado","$15.000,00","Disponible"
"Escribiendo la nueva historia","Laura Esquivel","Usado","$5.000,00","Disponible"
"El lector","Bernard Schlink","Usado","$9.000,00","Disponible"
"El primer café del día","Toshikazu Kawaguchi","Usado","$13.000,00","Disponible"
"El pasillo de la muerte","Stephen King","Usado","$13.000,00","Disponible"
"Fausto","Goethe","Usado","$6.000,00","Vendido"
"Freshwater","Virginia Woolf","Usado","$6.000,00","Disponible"
"Grey","E. L. James","Usado","$5.000,00","Disponible"
"Junto a un muerto y otros cuentos de terror","Guy de Maupassant","Usado","$7.000,00","Vendido"
"Juicio Final","John Katzenbach","Usado","$12.000,00","Disponible"
"La barca sin pescador","Alejandro Casona","Usado","$7.000,00","Disponible"
"La casa de Bernarda Alba","Federico García Lorca","Usado","$3.000,00","Disponible"
"La casa de las bellas durmientes","Yasunari Kawabata","Usado","$10.000,00","Disponible"
"La chica del tren","Paula Hawkins","Usado","$12.000,00","Disponible"
"La dama de blanco","Wilkie Collins","Usado","$7.500,00","Disponible"
"La hija única","Guadalupe Nettel","Usado","$16.000,00","Disponible"
"La forma del agua","Del toro & Kraus","Usado","$14.000,00","Vendido"
"Llamame por tu nombre","André Aciman","Usado","$17.000,00","Disponible"
"La nostalgia feliz","Amelie Nothomb","Usado","$12.000,00","Disponible"
"La primavera llegó en un carro tirado por caballos","Riichi Yokomitsu","Usado","$10.000,00","Disponible"
"Larvas","Tamara Silva Bernaschina","Usado","$12.000,00","Disponible"
"La sociedad del espectáculo","Guy Debord","Usado","$15.000,00","Disponible"
"La sangre se esparce rápidamente","Ed Wood","Usado","$8.000,00","Vendido"
"La vegetariana","Han Kang","Usado","$12.000,00","Vendido"
"La vida por delante","Magalí Etchebarne","Usado","$14.000,00","Disponible"
"Las partículas elementales","Michel Houllebecq","Usado","$10.000,00","Disponible"
"Los artistas y la política","Virginia Woolf","Usado","$14.000,00","Disponible"
"Los caballeros las prefieren rubias...","Anita Loos","Usado","$5.000,00","Disponible"
"Los puentes de Madison County","Robert J. Waller","Usado","$9.000,00","Disponible"
"Maum","Hwang Seung Ok","Usado","$15.000,00","Disponible"
"Musica de Cañerías","Charles Bukowski","Usado","$6.000,00","Disponible"
"Nené","Cesare Lanza","Usado","$3.000,00","Disponible"
"Opus Nigrum","Marguerite Yourcenar","Usado","$7.000,00","Disponible"
"Orgullo y prejuicio (Ed. Alianza)","Jane Austen","Usado","$15.000,00","Disponible"
"Panorama de la Psicopatología Infantil","Walter Mario Frutos","Usado","$3.500,00","Disponible"
"Psicología General","Davini, de Salluzzi, Rossi","Usado","$5.000,00","Vendido"
"Primera persona del singular","Haruki Murakami","Usado","$9.000,00","Vendido"
"Rebecca","Daphne Du Maurier","Usado","$18.000,00","Disponible"
"The end of the f*cking world","Charles Forsman","Usado","$9.000,00","Vendido"
"Te llevaré a un lugar donde todo es posible","Laurent Gonnelle","Usado","$8.000,00","Disponible"
"The Man in the Iron Mask (Inglés)","Alexandre Dumas","Usado","$5.000,00","Disponible"
"Un árbol de la noche","Truman Capote","Usado","$7.000,00","Disponible"
"Una casa llena de gente","Mariana Sández","Usado","$15.000,00","Disponible"
"Vida líquida","Zygmunt Bauman","Usado","$9.000,00","Disponible"
"2001: Una odisea espacial","Arthur Clarke","Usado","$6.000,00","Disponible"
`;
